export type BestBar = {
  rank: number;
  name: string;
  city: string;
  country: string;
  notes?: string;
};

export const bestBars: BestBar[] = [
  { rank: 1, name: "Bar 1", city: "City 1", country: "Country 1" },
  { rank: 2, name: "Bar 2", city: "City 2", country: "Country 2" },
  { rank: 3, name: "Bar 3", city: "City 3", country: "Country 3" },
  { rank: 4, name: "Bar 4", city: "City 4", country: "Country 4" },
  { rank: 5, name: "Bar 5", city: "City 5", country: "Country 5" },
  { rank: 6, name: "Bar 6", city: "City 6", country: "Country 6" },
  { rank: 7, name: "Bar 7", city: "City 7", country: "Country 7" },
  { rank: 8, name: "Bar 8", city: "City 8", country: "Country 8" },
  { rank: 9, name: "Bar 9", city: "City 9", country: "Country 9" },
  { rank: 10, name: "Bar 10", city: "City 10", country: "Country 10" },
  { rank: 11, name: "Bar 11", city: "City 11", country: "Country 11" },
  { rank: 12, name: "Bar 12", city: "City 12", country: "Country 12" },
  { rank: 13, name: "Bar 13", city: "City 13", country: "Country 13" },
  { rank: 14, name: "Bar 14", city: "City 14", country: "Country 14" },
  { rank: 15, name: "Bar 15", city: "City 15", country: "Country 15" },
  { rank: 16, name: "Bar 16", city: "City 16", country: "Country 16" },
  { rank: 17, name: "Bar 17", city: "City 17", country: "Country 17" },
  { rank: 18, name: "Bar 18", city: "City 18", country: "Country 18" },
  { rank: 19, name: "Bar 19", city: "City 19", country: "Country 19" },
  { rank: 20, name: "Bar 20", city: "City 20", country: "Country 20" },
  { rank: 21, name: "Bar 21", city: "City 21", country: "Country 21" },
  { rank: 22, name: "Bar 22", city: "City 22", country: "Country 22" },
  { rank: 23, name: "Bar 23", city: "City 23", country: "Country 23" },
  { rank: 24, name: "Bar 24", city: "City 24", country: "Country 24" },
  { rank: 25, name: "Bar 25", city: "City 25", country: "Country 25" },
  { rank: 26, name: "Bar 26", city: "City 26", country: "Country 26" },
  { rank: 27, name: "Bar 27", city: "City 27", country: "Country 27" },
  { rank: 28, name: "Bar 28", city: "City 28", country: "Country 28" },
  { rank: 29, name: "Bar 29", city: "City 29", country: "Country 29" },
  { rank: 30, name: "Bar 30", city: "City 30", country: "Country 30" },
  { rank: 31, name: "Bar 31", city: "City 31", country: "Country 31" },
  { rank: 32, name: "Bar 32", city: "City 32", country: "Country 32" },
  { rank: 33, name: "Bar 33", city: "City 33", country: "Country 33" },
  { rank: 34, name: "Bar 34", city: "City 34", country: "Country 34" },
  { rank: 35, name: "Bar 35", city: "City 35", country: "Country 35" },
  { rank: 36, name: "Bar 36", city: "City 36", country: "Country 36" },
  { rank: 37, name: "Bar 37", city: "City 37", country: "Country 37" },
  { rank: 38, name: "Bar 38", city: "City 38", country: "Country 38" },
  { rank: 39, name: "Bar 39", city: "City 39", country: "Country 39" },
  { rank: 40, name: "Bar 40", city: "City 40", country: "Country 40" },
  { rank: 41, name: "Bar 41", city: "City 41", country: "Country 41" },
  { rank: 42, name: "Bar 42", city: "City 42", country: "Country 42" },
  { rank: 43, name: "Bar 43", city: "City 43", country: "Country 43" },
  { rank: 44, name: "Bar 44", city: "City 44", country: "Country 44" },
  { rank: 45, name: "Bar 45", city: "City 45", country: "Country 45" },
  { rank: 46, name: "Bar 46", city: "City 46", country: "Country 46" },
  { rank: 47, name: "Bar 47", city: "City 47", country: "Country 47" },
  { rank: 48, name: "Bar 48", city: "City 48", country: "Country 48" },
  { rank: 49, name: "Bar 49", city: "City 49", country: "Country 49" },
  { rank: 50, name: "Bar 50", city: "City 50", country: "Country 50" },
];
